variables:
  type: 'Transpile'
  versionSpec: '10.x'
  ghRef: 'github.com/starlight-ts/inlustris'
  targetBranch: 'build'

trigger:
  branches:
    include:
      - master
    exclude:
      - build

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(versionSpec)
    displayName: 'Install Node'
  - script: yarn
    displayName: 'Install Dependencies'
  - script: yarn lint
    displayName: 'Test Lint'
  - bash: |
      set -e

      if [["$BRANCH" != "master" ]]; then
        echo -e "Not building for a non branch push - skipping"
        exit 0
      fi

      echo -e "Building for a branch push - building and deploying"
      REPO=$(git config remote.origin.url)
      SHA=$(git rev-parse --verify HEAD)

      git clone $REPO out -b $TARGET_BRANCH

      yarn run build

      mv dist out/lib

      cd out
      git add --all .
      git config user.name "Azure Pipelines"
      git config user.email "${COMMIT_EMAIL}"
      git commit -m "${TYPE} build: ${SHA}" || true
      git push "https://${GH_TOKEN}@${GH_REF}" $TARGET_BRANCH
    env:
      GH_TOKEN: $(ghToken)
      COMMIT_EMAIL: $(commitEmail)
      TYPE: $(type)
      GH_REF: $(ghRef)
      BRANCH: $(Build.SourceBranchName)
      TARGET_BRANCH: $(targetBranch)
    displayName: Build $(type)